# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'index.ui'
#
# Created by: PyQt5 UI code generator 5.4.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(906, 735)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setText("")
        self.frame.setObjectName("frame")
        self.horizontalLayout_3.addWidget(self.frame)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("FreeMono")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(134, 134, 134);")
        self.label_3.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_3.setLineWidth(10)
        self.label_3.setMidLineWidth(10)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 0, 0, 1, 1)
        self.menu_list = QtWidgets.QTreeWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menu_list.sizePolicy().hasHeightForWidth())
        self.menu_list.setSizePolicy(sizePolicy)
        self.menu_list.setAutoFillBackground(True)
        self.menu_list.setStyleSheet("")
        self.menu_list.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.menu_list.setFrameShadow(QtWidgets.QFrame.Plain)
        self.menu_list.setLineWidth(1)
        self.menu_list.setAutoScroll(False)
        self.menu_list.setTabKeyNavigation(False)
        self.menu_list.setProperty("showDropIndicator", True)
        self.menu_list.setAlternatingRowColors(True)
        self.menu_list.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.menu_list.setTextElideMode(QtCore.Qt.ElideRight)
        self.menu_list.setAutoExpandDelay(1)
        self.menu_list.setRootIsDecorated(False)
        self.menu_list.setItemsExpandable(True)
        self.menu_list.setAnimated(True)
        self.menu_list.setAllColumnsShowFocus(True)
        self.menu_list.setHeaderHidden(True)
        self.menu_list.setObjectName("menu_list")
        item_0 = QtWidgets.QTreeWidgetItem(self.menu_list)
        font = QtGui.QFont()
        font.setFamily("Waree")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        item_0.setFont(0, font)
        brush = QtGui.QBrush(QtGui.QColor(6, 6, 6))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item_0.setBackground(0, brush)
        brush = QtGui.QBrush(QtGui.QColor(249, 249, 249))
        brush.setStyle(QtCore.Qt.NoBrush)
        item_0.setForeground(0, brush)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setItalic(True)
        item_1.setFont(0, font)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setItalic(True)
        item_1.setFont(0, font)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setItalic(True)
        item_1.setFont(0, font)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setItalic(True)
        item_1.setFont(0, font)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setItalic(True)
        item_1.setFont(0, font)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setItalic(True)
        item_1.setFont(0, font)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setItalic(True)
        item_1.setFont(0, font)
        item_0 = QtWidgets.QTreeWidgetItem(self.menu_list)
        font = QtGui.QFont()
        font.setFamily("Waree")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        item_0.setFont(0, font)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item_0.setBackground(0, brush)
        brush = QtGui.QBrush(QtGui.QColor(245, 245, 245))
        brush.setStyle(QtCore.Qt.NoBrush)
        item_0.setForeground(0, brush)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setItalic(True)
        item_1.setFont(0, font)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setItalic(True)
        item_1.setFont(0, font)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setItalic(True)
        item_1.setFont(0, font)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setItalic(True)
        item_1.setFont(0, font)
        item_0 = QtWidgets.QTreeWidgetItem(self.menu_list)
        font = QtGui.QFont()
        font.setFamily("Waree")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        item_0.setFont(0, font)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item_0.setBackground(0, brush)
        brush = QtGui.QBrush(QtGui.QColor(248, 248, 248))
        brush.setStyle(QtCore.Qt.NoBrush)
        item_0.setForeground(0, brush)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setItalic(True)
        item_1.setFont(0, font)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setItalic(True)
        item_1.setFont(0, font)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setItalic(True)
        item_1.setFont(0, font)
        item_0 = QtWidgets.QTreeWidgetItem(self.menu_list)
        font = QtGui.QFont()
        font.setFamily("Waree")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        item_0.setFont(0, font)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item_0.setBackground(0, brush)
        brush = QtGui.QBrush(QtGui.QColor(250, 250, 250))
        brush.setStyle(QtCore.Qt.NoBrush)
        item_0.setForeground(0, brush)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setItalic(True)
        item_1.setFont(0, font)
        self.gridLayout_2.addWidget(self.menu_list, 1, 0, 1, 1)
        self.horizontalLayout_3.addLayout(self.gridLayout_2)
        self.horizontalLayout_2.addLayout(self.horizontalLayout_3)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", "Menu"))
        self.menu_list.headerItem().setText(0, _translate("MainWindow", "menu"))
        __sortingEnabled = self.menu_list.isSortingEnabled()
        self.menu_list.setSortingEnabled(False)
        self.menu_list.topLevelItem(0).setText(0, _translate("MainWindow", "Face Recognition"))
        self.menu_list.topLevelItem(0).child(0).setText(0, _translate("MainWindow", "人脸检测"))
        self.menu_list.topLevelItem(0).child(1).setText(0, _translate("MainWindow", "人脸识别"))
        self.menu_list.topLevelItem(0).child(2).setText(0, _translate("MainWindow", "人脸考勤"))
        self.menu_list.topLevelItem(0).child(3).setText(0, _translate("MainWindow", "人脸检索"))
        self.menu_list.topLevelItem(0).child(4).setText(0, _translate("MainWindow", "单脸注册"))
        self.menu_list.topLevelItem(0).child(5).setText(0, _translate("MainWindow", "多脸注册"))
        self.menu_list.topLevelItem(0).child(6).setText(0, _translate("MainWindow", "身份证注册"))
        self.menu_list.topLevelItem(1).setText(0, _translate("MainWindow", "Speech Interaction"))
        self.menu_list.topLevelItem(1).child(0).setText(0, _translate("MainWindow", "语音识别"))
        self.menu_list.topLevelItem(1).child(1).setText(0, _translate("MainWindow", "语音检索"))
        self.menu_list.topLevelItem(1).child(2).setText(0, _translate("MainWindow", "语音考勤"))
        self.menu_list.topLevelItem(1).child(3).setText(0, _translate("MainWindow", "语音注册"))
        self.menu_list.topLevelItem(2).setText(0, _translate("MainWindow", "Data Management"))
        self.menu_list.topLevelItem(2).child(0).setText(0, _translate("MainWindow", "数据导出"))
        self.menu_list.topLevelItem(2).child(1).setText(0, _translate("MainWindow", "数据导入"))
        self.menu_list.topLevelItem(2).child(2).setText(0, _translate("MainWindow", "统计查看"))
        self.menu_list.topLevelItem(3).setText(0, _translate("MainWindow", "System Option"))
        self.menu_list.topLevelItem(3).child(0).setText(0, _translate("MainWindow", "参数配置"))
        self.menu_list.setSortingEnabled(__sortingEnabled)

