# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'index.ui'
#
# Created by: PyQt5 UI code generator 5.4.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Index_UI(object):
    def setupUi(self, Index_UI):
        Index_UI.setObjectName("Index_UI")
        Index_UI.resize(908, 736)
        self.centralwidget = QtWidgets.QWidget(Index_UI)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.main_layout = QtWidgets.QHBoxLayout()
        self.main_layout.setSpacing(0)
        self.main_layout.setObjectName("main_layout")
        self.frame = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setText("")
        self.frame.setObjectName("frame")
        self.main_layout.addWidget(self.frame)
        self.show_hide = QtWidgets.QToolButton(self.centralwidget)
        self.show_hide.setStyleSheet("border-radius:9px;\n"
"border:1px;\n"
"background-color:black;\n"
"color:white;")
        self.show_hide.setPopupMode(QtWidgets.QToolButton.DelayedPopup)
        self.show_hide.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.show_hide.setAutoRaise(False)
        self.show_hide.setArrowType(QtCore.Qt.RightArrow)
        self.show_hide.setObjectName("show_hide")
        self.main_layout.addWidget(self.show_hide)
        self.menu_layout = QtWidgets.QGridLayout()
        self.menu_layout.setSpacing(0)
        self.menu_layout.setObjectName("menu_layout")
        self.menu = QtWidgets.QTreeWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menu.sizePolicy().hasHeightForWidth())
        self.menu.setSizePolicy(sizePolicy)
        self.menu.setAutoFillBackground(True)
        self.menu.setStyleSheet("")
        self.menu.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.menu.setFrameShadow(QtWidgets.QFrame.Plain)
        self.menu.setLineWidth(1)
        self.menu.setAutoScroll(False)
        self.menu.setTabKeyNavigation(False)
        self.menu.setProperty("showDropIndicator", True)
        self.menu.setAlternatingRowColors(True)
        self.menu.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.menu.setTextElideMode(QtCore.Qt.ElideRight)
        self.menu.setAutoExpandDelay(1)
        self.menu.setRootIsDecorated(False)
        self.menu.setItemsExpandable(True)
        self.menu.setAnimated(True)
        self.menu.setAllColumnsShowFocus(True)
        self.menu.setHeaderHidden(True)
        self.menu.setObjectName("menu")
        item_0 = QtWidgets.QTreeWidgetItem(self.menu)
        font = QtGui.QFont()
        font.setFamily("Waree")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        item_0.setFont(0, font)
        brush = QtGui.QBrush(QtGui.QColor(6, 6, 6))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item_0.setBackground(0, brush)
        brush = QtGui.QBrush(QtGui.QColor(249, 249, 249))
        brush.setStyle(QtCore.Qt.NoBrush)
        item_0.setForeground(0, brush)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setItalic(True)
        item_1.setFont(0, font)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setItalic(True)
        item_1.setFont(0, font)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setItalic(True)
        item_1.setFont(0, font)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setItalic(True)
        item_1.setFont(0, font)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setItalic(True)
        item_1.setFont(0, font)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setItalic(True)
        item_1.setFont(0, font)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setItalic(True)
        item_1.setFont(0, font)
        item_0 = QtWidgets.QTreeWidgetItem(self.menu)
        font = QtGui.QFont()
        font.setFamily("Waree")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        item_0.setFont(0, font)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item_0.setBackground(0, brush)
        brush = QtGui.QBrush(QtGui.QColor(245, 245, 245))
        brush.setStyle(QtCore.Qt.NoBrush)
        item_0.setForeground(0, brush)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setItalic(True)
        item_1.setFont(0, font)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setItalic(True)
        item_1.setFont(0, font)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setItalic(True)
        item_1.setFont(0, font)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setItalic(True)
        item_1.setFont(0, font)
        item_0 = QtWidgets.QTreeWidgetItem(self.menu)
        font = QtGui.QFont()
        font.setFamily("Waree")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        item_0.setFont(0, font)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item_0.setBackground(0, brush)
        brush = QtGui.QBrush(QtGui.QColor(248, 248, 248))
        brush.setStyle(QtCore.Qt.NoBrush)
        item_0.setForeground(0, brush)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setItalic(True)
        item_1.setFont(0, font)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setItalic(True)
        item_1.setFont(0, font)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setItalic(True)
        item_1.setFont(0, font)
        item_0 = QtWidgets.QTreeWidgetItem(self.menu)
        font = QtGui.QFont()
        font.setFamily("Waree")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        item_0.setFont(0, font)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item_0.setBackground(0, brush)
        brush = QtGui.QBrush(QtGui.QColor(250, 250, 250))
        brush.setStyle(QtCore.Qt.NoBrush)
        item_0.setForeground(0, brush)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setItalic(True)
        item_1.setFont(0, font)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        self.menu_layout.addWidget(self.menu, 0, 1, 1, 1)
        self.item_list = QtWidgets.QFormLayout()
        self.item_list.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.item_list.setRowWrapPolicy(QtWidgets.QFormLayout.WrapAllRows)
        self.item_list.setLabelAlignment(QtCore.Qt.AlignCenter)
        self.item_list.setFormAlignment(QtCore.Qt.AlignCenter)
        self.item_list.setContentsMargins(5, 5, 5, 5)
        self.item_list.setObjectName("item_list")
        self.nameLabel = QtWidgets.QLabel(self.centralwidget)
        self.nameLabel.setObjectName("nameLabel")
        self.item_list.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.nameLabel)
        self.iDLabel = QtWidgets.QLabel(self.centralwidget)
        self.iDLabel.setObjectName("iDLabel")
        self.item_list.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.iDLabel)
        self.dateLabel = QtWidgets.QLabel(self.centralwidget)
        self.dateLabel.setObjectName("dateLabel")
        self.item_list.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.dateLabel)
        self.name = QtWidgets.QLabel(self.centralwidget)
        self.name.setObjectName("name")
        self.item_list.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.name)
        self.id_num = QtWidgets.QLabel(self.centralwidget)
        self.id_num.setObjectName("id_num")
        self.item_list.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.id_num)
        self.date = QtWidgets.QLabel(self.centralwidget)
        self.date.setObjectName("date")
        self.item_list.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.date)
        self.menu_layout.addLayout(self.item_list, 2, 1, 1, 1)
        self.status = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.status.sizePolicy().hasHeightForWidth())
        self.status.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(36)
        self.status.setFont(font)
        self.status.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.status.setText("")
        self.status.setAlignment(QtCore.Qt.AlignCenter)
        self.status.setObjectName("status")
        self.menu_layout.addWidget(self.status, 1, 1, 1, 1)
        self.menu_layout.setRowStretch(0, 3)
        self.menu_layout.setRowStretch(1, 1)
        self.menu_layout.setRowStretch(2, 1)
        self.main_layout.addLayout(self.menu_layout)
        self.main_layout.setStretch(0, 8)
        self.main_layout.setStretch(2, 4)
        self.horizontalLayout_2.addLayout(self.main_layout)
        Index_UI.setCentralWidget(self.centralwidget)

        self.retranslateUi(Index_UI)
        QtCore.QMetaObject.connectSlotsByName(Index_UI)

    def retranslateUi(self, Index_UI):
        _translate = QtCore.QCoreApplication.translate
        Index_UI.setWindowTitle(_translate("Index_UI", "MainWindow"))
        self.show_hide.setText(_translate("Index_UI", "..."))
        self.show_hide.setShortcut(_translate("Index_UI", "F1"))
        self.menu.headerItem().setText(0, _translate("Index_UI", "menu"))
        __sortingEnabled = self.menu.isSortingEnabled()
        self.menu.setSortingEnabled(False)
        self.menu.topLevelItem(0).setText(0, _translate("Index_UI", "Face Recognition"))
        self.menu.topLevelItem(0).child(0).setText(0, _translate("Index_UI", "人脸检测"))
        self.menu.topLevelItem(0).child(1).setText(0, _translate("Index_UI", "人脸识别"))
        self.menu.topLevelItem(0).child(2).setText(0, _translate("Index_UI", "人脸考勤"))
        self.menu.topLevelItem(0).child(3).setText(0, _translate("Index_UI", "人脸检索"))
        self.menu.topLevelItem(0).child(4).setText(0, _translate("Index_UI", "单脸注册"))
        self.menu.topLevelItem(0).child(5).setText(0, _translate("Index_UI", "多脸注册"))
        self.menu.topLevelItem(0).child(6).setText(0, _translate("Index_UI", "身份证注册"))
        self.menu.topLevelItem(1).setText(0, _translate("Index_UI", "Speech Interaction"))
        self.menu.topLevelItem(1).child(0).setText(0, _translate("Index_UI", "语音识别"))
        self.menu.topLevelItem(1).child(1).setText(0, _translate("Index_UI", "语音检索"))
        self.menu.topLevelItem(1).child(2).setText(0, _translate("Index_UI", "语音考勤"))
        self.menu.topLevelItem(1).child(3).setText(0, _translate("Index_UI", "语音注册"))
        self.menu.topLevelItem(2).setText(0, _translate("Index_UI", "Data Management"))
        self.menu.topLevelItem(2).child(0).setText(0, _translate("Index_UI", "数据导出"))
        self.menu.topLevelItem(2).child(1).setText(0, _translate("Index_UI", "数据导入"))
        self.menu.topLevelItem(2).child(2).setText(0, _translate("Index_UI", "统计查看"))
        self.menu.topLevelItem(3).setText(0, _translate("Index_UI", "System Option"))
        self.menu.topLevelItem(3).child(0).setText(0, _translate("Index_UI", "参数配置"))
        self.menu.topLevelItem(3).child(1).setText(0, _translate("Index_UI", "模型性能可视化"))
        self.menu.setSortingEnabled(__sortingEnabled)
        self.nameLabel.setText(_translate("Index_UI", "Name:"))
        self.iDLabel.setText(_translate("Index_UI", "ID:"))
        self.dateLabel.setText(_translate("Index_UI", "Date:"))
        self.name.setText(_translate("Index_UI", "TextLabel"))
        self.id_num.setText(_translate("Index_UI", "TextLabel"))
        self.date.setText(_translate("Index_UI", "TextLabel"))

