# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sys_option.ui'
#
# Created by: PyQt5 UI code generator 5.4.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_sys_option(object):
    def setupUi(self, sys_option):
        sys_option.setObjectName("sys_option")
        sys_option.resize(296, 300)
        sys_option.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.buttonBox = QtWidgets.QDialogButtonBox(sys_option)
        self.buttonBox.setGeometry(QtCore.QRect(100, 240, 171, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.formLayoutWidget = QtWidgets.QWidget(sys_option)
        self.formLayoutWidget.setGeometry(QtCore.QRect(60, 50, 191, 194))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setItalic(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.recognition_count = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setItalic(True)
        self.recognition_count.setFont(font)
        self.recognition_count.setText("")
        self.recognition_count.setAlignment(QtCore.Qt.AlignCenter)
        self.recognition_count.setObjectName("recognition_count")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.recognition_count)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setItalic(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.sign_in_count = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setItalic(True)
        self.sign_in_count.setFont(font)
        self.sign_in_count.setText("")
        self.sign_in_count.setAlignment(QtCore.Qt.AlignCenter)
        self.sign_in_count.setObjectName("sign_in_count")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.sign_in_count)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setItalic(True)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.interval = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setItalic(True)
        self.interval.setFont(font)
        self.interval.setText("")
        self.interval.setAlignment(QtCore.Qt.AlignCenter)
        self.interval.setObjectName("interval")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.interval)
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setItalic(True)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.detect_coint = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setItalic(True)
        self.detect_coint.setFont(font)
        self.detect_coint.setText("")
        self.detect_coint.setAlignment(QtCore.Qt.AlignCenter)
        self.detect_coint.setObjectName("detect_coint")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.detect_coint)

        self.retranslateUi(sys_option)
        self.buttonBox.accepted.connect(sys_option.accept)
        self.buttonBox.rejected.connect(sys_option.reject)
        QtCore.QMetaObject.connectSlotsByName(sys_option)

    def retranslateUi(self, sys_option):
        _translate = QtCore.QCoreApplication.translate
        sys_option.setWindowTitle(_translate("sys_option", "System Option"))
        self.label.setText(_translate("sys_option", "识别帧数"))
        self.label_2.setText(_translate("sys_option", "注册帧数"))
        self.label_3.setText(_translate("sys_option", "休眠间隔"))
        self.label_4.setText(_translate("sys_option", "检测帧数"))

